apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: myacr.azurecr.io/backend:latest  # Replace with your ACR
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-cluster:27017/app-db"  # Change as per CosmosDB
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: acr-secret
